ci:
  autofix_prs: false
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: name-tests-test
  - repo: 'https://github.com/codespell-project/codespell'
    rev: v2.3.0
    hooks:
      - id: codespell
